web-ecommerce-app/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from api.register import RegisterViewSet
from api.products import ProductViewSet

router = DefaultRouter()
router.register(r'register', RegisterViewSet, basename='register')
router.register(r'products', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

web-ecommerce-app/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from ecommerce.views import homepage_view

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),
    path('', homepage_view),
    path('products/', include('products.urls')),
    path('stores/', include('stores.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('payments/', include('payments.urls')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-ecommerce-app/payments/urls.py
from django.urls import path
from payments.views import (
    add_card, show_cards, delete_card, order, process, handle_succeeded_payment, handle_failed_payment,
    show_orders, show_order_details
)

app_name = 'payments'

urlpatterns = [
    path('add-card/', add_card, name='add_card'),
    path('cards/', show_cards, name='cards'),
    path('delete_card/<int:card_id>/', delete_card, name='delete_card'),
    path('order/', order, name='order'),
    path('process/', process, name='process'),
    path('succeeded/', handle_succeeded_payment, name='succeeded'),
    path('failed/', handle_failed_payment, name='failed'),
    path('orders/', show_orders, name='orders'),
    path('orders/<int:order_id>/', show_order_details, name='order_details'),
]

web-ecommerce-app/products/urls.py
from django.urls import path
from products.views import show_all_products, show_product_details, add_product_to_cart, show_checkout, remove_product_from_cart

app_name = 'products'

urlpatterns = [
    path('', show_all_products, name='all'),  # this is already localhost:8000/products/
    path('<int:product_id>/', show_product_details, name='details'),
    path('<int:product_id>/add_to_cart', add_product_to_cart, name='add_to_cart'),  # localhost:8000/products/<p_id>/add_to_cart
    path('checkout/', show_checkout, name='checkout'),
    path('<int:product_id>/remove_from_cart/', remove_product_from_cart, name='remove_from_cart'),
]

web-ecommerce-app/stores/urls.py
from django.urls import path
from stores.views import show_stores, show_details

app_name = 'stores'

urlpatterns = [
    path('', show_stores, name='all'),
    path('<int:id>/', show_details, name='details')
]

web-ecommerce-app/users/urls.py
from django.urls import path, include
from users.views import login_user, register_user, logout_user, show_profile, activate, regenerate_token

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_user, name='register'),
    path('profile/', show_profile, name='profile'),
    path('activate/<str:token>/', activate, name='activate'),
    path('regenerate_token/<str:token>/', regenerate_token, name='regenerate_token'),
    path('social-auth/', include('social_django.urls')),
]

web-ecommerce-app/templates/base.html
<html>
    <head>
        {% block title %}
        {% endblock %}

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block styles %}
        {% endblock %}

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        {% block hscript %}
        {% endblock %}
    </head>
    <body>
        {% include 'menu.html' %}
        {% block content %}
        {% endblock %}
        {% block bscript %}
        {% endblock %}
    </body>
</html>

web-ecommerce-app/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>My first Django homepage</title>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/homepage.css' %}" />
{% endblock %}

{% block content %}
    <h1>
        <img src="{% static 'images/djangoLogo.png' %}" width="75" />
        <span>{{ title }}</span>
    </h1>
    <h2>Homepage</h2>
    <h3>Services</h3>
    <ul>
        {% for service in services %}
            <li style="margin-bottom: 10px; {% if not forloop.counter0|divisibleby:2 %}background-color: #eee;{% endif %}">
                {{ forloop.counter0 }} <strong>{{ service.name }}</strong>: {{ service.value }}
            </li>
        {% endfor %}
    </ul>
    <p>Python is an interpreted high-level general-purpose programming language. Its design philosophy emphasizes code readability with its use of significant indentation. Its language constructs as well as its object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.[30]

Python is dynamically-typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly, procedural), object-oriented and functional programming. It is often described as a "batteries included" language due to its comprehensive standard library.[31]

Guido van Rossum began working on Python in the late 1980s, as a successor to the ABC programming language, and first released it in 1991 as Python 0.9.0.[32] Python 2.0 was released in 2000 and introduced new features, such as list comprehensions and a garbage collection system using reference counting. Python 3.0 was released in 2008 and was a major revision of the language that is not completely backward-compatible. Python 2 was discontinued with version 2.7.18 in 2020.[33]</p>
<a class="btn btn-danger" href="https://en.wikipedia.org/wiki/Python_(programming_language)" target="_blank">View more...</a>

<div class="container">
    <div class="row">
        <div class="col-12">
            Col 12
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            Col 6
        </div>
        <div class="col-6">
            Col 6
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            Col 4
        </div>
        <div class="col-4">
            Col 4
        </div>
        <div class="col-4">
            Col 4
        </div>
    </div>
    <br/><br/>
    <div class="row">
        <div class="col-12 col-md-6 col-lg-3">
            Col 3
        </div>
        <div class="col-12 col-md-6 col-lg-3">
            Col 3
        </div>
        <div class="col-12 col-md-6 col-lg-3">
            Col 3
        </div>
        <div class="col-12 col-md-6 col-lg-3">
            Col 3
        </div>
    </div>
    <br/><br/>
    <div class="row">
        <div class="col-2" style="background-color: red">
            Col 2
        </div>
        <div class="col-6" style="background-color: blue">
            Col 6
        </div>
        <div class="col-4" style="background-color: green">
            Col 4
        </div>
    </div>
</div>

{% endblock %}

web-ecommerce-app/templates/menu.html
{% load cart %}
{% load notifications %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <nav>
                <a href="/">Homepage</a>
                <a href="{% url 'products:all' %}">Products</a>
                <a href="{% url 'stores:all' %}">Stores</a>
                {% if request.user.is_authenticated %}
                    {% cart_link request.session %}
                    <a href="{% url 'payments:orders' %}">Orders</a>
                    <a href="{% url 'payments:cards' %}">Payment methods</a>
                    <a href="{% url 'notifications:view_all' %}">Notifications ({{ request.user.notifications | unseen }})</a>
                    {% if request.user.is_superuser %}
                        <a href="/admin">Admin</a>
                    {% endif %}
                    <a href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}">Login</a>
                    <a href="{% url 'users:register' %}">Register</a>
                {% endif %}
            </nav>
        </div>
    </div>
</div>