web-ecommerce-app/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from api.register import RegisterViewSet
from api.products import ProductViewSet

router = DefaultRouter()
router.register(r'register', RegisterViewSet, basename='register')
router.register(r'products', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

web-ecommerce-app/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from ecommerce.views import homepage_view

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),
    path('', homepage_view),
    path('products/', include('products.urls')),
    path('stores/', include('stores.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('payments/', include('payments.urls')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-ecommerce-app/payments/urls.py
from django.urls import path
from payments.views import (
    add_card, show_cards, delete_card, order, process, handle_succeeded_payment, handle_failed_payment,
    show_orders, show_order_details
)

app_name = 'payments'

urlpatterns = [
    path('add-card/', add_card, name='add_card'),
    path('cards/', show_cards, name='cards'),
    path('delete_card/<int:card_id>/', delete_card, name='delete_card'),
    path('order/', order, name='order'),
    path('process/', process, name='process'),
    path('succeeded/', handle_succeeded_payment, name='succeeded'),
    path('failed/', handle_failed_payment, name='failed'),
    path('orders/', show_orders, name='orders'),
    path('orders/<int:order_id>/', show_order_details, name='order_details'),
]

web-ecommerce-app/products/urls.py
from django.urls import path
from products.views import show_all_products, show_product_details, add_product_to_cart, show_checkout, remove_product_from_cart

app_name = 'products'

urlpatterns = [
    path('', show_all_products, name='all'),  # this is already localhost:8000/products/
    path('<int:product_id>/', show_product_details, name='details'),
    path('<int:product_id>/add_to_cart', add_product_to_cart, name='add_to_cart'),  # localhost:8000/products/<p_id>/add_to_cart
    path('checkout/', show_checkout, name='checkout'),
    path('<int:product_id>/remove_from_cart/', remove_product_from_cart, name='remove_from_cart'),
]

web-ecommerce-app/products/models.py
from django.db import models
from django.contrib.auth import get_user_model
from utils import XS, S, M, L, XL, XXL
from utils.constants.size import SIZES
from stores.models import Store

AuthUserModel = get_user_model()


class Category(models.Model):
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('-id',)

    name = models.CharField(max_length=128, null=False)

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<Category ID=%s | name="%s"' % (self.id, self.name)


class Product(models.Model):
    class Meta:
        ordering = ['id']

    name = models.CharField(max_length=128, null=False)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name='products', default=None, null=True)
    # category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='products', null=True, default=None)
    # category = models.ManyToManyField(Category, related_name='products')
    categories = models.ManyToManyField(Category, through='ProductCategory', related_name='products')
    quantity = models.IntegerField(default=0, null=False)
    price = models.DecimalField(max_digits=5, decimal_places=2)  # max => 999.99
    color = models.CharField(max_length=10, null=False)
    size = models.IntegerField(choices=((XS, 'XS'), (S, 'S'), (M, 'M'), (L, 'L'), (XL, 'XL'), (XXL, 'XXL')))
    gender = models.CharField(choices=(('M', 'male'), ('F', 'female')), max_length=1)

    @property
    def human_size(self):
        return SIZES.get(self.size, None)

    def store_name(self):
        if hasattr(self.store, 'name'):
            return self.store.name

        return '-'

    store_name.short_description = 'shop name'
    store_name.admin_order_field = 'store__name'

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<Product object ID = {self.id}>'


class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'product category'
        verbose_name_plural = 'product categories'

    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='categories_pivot')  # product.categories[0].category.name
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='products_pivot')  # category.products[0].product.name
    extra_column = models.IntegerField(null=True, default=None)

web-ecommerce-app/users/models/details.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from django.utils import timezone
from utils.constants.activation import ACTIVATION_DICT


def expires_at_time():
    return timezone.now() + timezone.timedelta(**ACTIVATION_DICT)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile_images/', null=True, default=None)

    @property
    def image(self):
        if self.avatar:
            return self.avatar.url

        return static('images/defaultUser.jpg')


class Activation(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activation')
    token = models.CharField(max_length=64, null=True, default=None, blank=False, unique=True)
    expires_at = models.DateTimeField(default=expires_at_time)
    activated_at = models.DateTimeField(null=True, default=None, blank=False)

    def __str__(self):
        return self.token

    def __repr__(self):
        return self.token


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')  # user.cart
    data = models.JSONField()

web-ecommerce-app/products/forms.py
from django import forms
from products.models import Category, Product
from payments.models import StripeCard

ORDER_BY_CHOICES = (('POPULARITY', 'Popularity'), ('PRICE_ASC', 'Price ascending'), ('PRICE_DESC', 'Price descending'))


def get_orderby_field(order_by):
    if order_by == 'PRICE_ASC':
        return 'price'

    if order_by == 'PRICE_DESC':
        return '-price'

    return 'id'


class FilterProductsForm(forms.Form):
    order_by = forms.ChoiceField(choices=ORDER_BY_CHOICES)
    categories = forms.MultipleChoiceField(choices=(), widget=forms.CheckboxSelectMultiple, required=False)
    min_price = forms.DecimalField(max_digits=5, decimal_places=2, required=False)
    max_price = forms.DecimalField(max_digits=5, decimal_places=2, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        categories = Category.objects.all()
        self.fields['categories'].choices = tuple((category.id, category.name) for category in categories)

    def clean_categories(self):
        categories = self.cleaned_data.get('categories', [])
        return categories

    def apply_filters(self):
        is_valid = self.is_valid()

        if is_valid:
            order_by = get_orderby_field(self.cleaned_data.get('order_by'))
            categories = self.cleaned_data.get('categories', [])
            min_price = self.cleaned_data.get('min_price')
            max_price = self.cleaned_data.get('max_price')

            products = Product.objects.order_by(order_by)

            if len(categories) > 0:
                products = products.filter(categories__id__in=categories)

            if min_price:
                products = products.filter(price__gte=min_price)

            if max_price:
                products = products.filter(price__lte=max_price)

            return products

        return Product.objects.all()


class SelectCardForm(forms.Form):
    card = forms.ChoiceField(choices=(), widget=forms.RadioSelect)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._user = user

        self.fields['card'].choices = tuple((card.id, card.number) for card in self._user.stripe_customer.cards.all())

    def clean_card(self):
        card_id = self.cleaned_data['card']

        try:
            card = StripeCard.objects.get(id=card_id)
        except StripeCard.DoesNotExist:
            card = None

        if card is None:
            raise forms.ValidationError('Selected card is invalid.')

        if card.stripe_customer.user.id != self._user.id:
            raise forms.ValidationError('Selected card is invalid.')

        return card

web-ecommerce-app/products/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect, reverse
from django.core.paginator import Paginator
from products.models import Product
from products.forms import FilterProductsForm, SelectCardForm
from utils.cart import Cart
from payments.utils import get_user_payment_methods_details


def show_all_products(request):
    form = FilterProductsForm(data=request.GET)
    products = form.apply_filters()

    paginator = Paginator(products, 4)
    page_obj = paginator.get_page(request.GET.get('page', 1))

    return render(request, 'products/products.html', {
        'page_obj': page_obj,
        'form': form,
    })


def show_product_details(request, product_id):
    # products = Product.objects.filter(id=product_id)
    # if len(products) == 0:
    #     raise Http404(f'Product with ID = {product_id} does not exists!')

    # try:
    #     product = Product.objects.get(id=product_id)
    # except Product.DoesNotExist:
    #     raise Http404(f'Product with ID = {product_id} does not exists!')
    # else:
    #     return render(request, 'products/details.html', {
    #         'product': product
    #     })

    # product = get_object_or_404(Product, id=product_id)
    product = get_object_or_404(Product, pk=product_id)

    return render(request, 'products/details.html', {
        'product': product,
    })


def add_product_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    quantity = request.POST.get('quantity')

    try:
        quantity = int(quantity)
    except (ValueError, TypeError):
        raise Http404('Quantity attribute is not valid.')

    cart = Cart(request)
    cart.add(product_id, quantity)

    return redirect(reverse('products:all'))


def show_checkout(request):
    cart = request.session.get('cart', {})
    products = Product.objects.filter(id__in=cart.keys())

    cart_items = [
        {
            "product": product,
            "quantity": cart[str(product.id)],
            "total": '%.2f' % (float(product.price) * int(cart[str(product.id)]))
        }
        for product in products
    ]

    # available_cards = get_user_payment_methods_details(request.user)

    select_card_form = SelectCardForm(request.user)

    return render(request, 'products/checkout.html', {
        'cart_items': cart_items,
        'cart': cart,
        # 'available_cards': available_cards,
        'select_card_form': select_card_form
    })


def remove_product_from_cart(request, product_id):
    get_object_or_404(Product, pk=product_id)

    cart = Cart(request)
    cart.remove(product_id)

    return redirect(reverse('products:checkout'))

web-ecommerce-app/products/templates/products/checkout.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        {% if cart_items|length == 0 %}
            <p>No product added to cart.</p>
        {% else %}
            <ul>
                {% for cart_item in cart_items %}
                    <li class="d-flex">
                        <div>
                            {{ cart_item.product.name }} - {{ cart_item.product.price }} RON - Qty: {{ cart_item.quantity }} - Total Price: {{ cart_item.total }}
                        </div>
                        <form method="post" action="{% url 'products:remove_from_cart' cart_item.product.id %}">
                            {% csrf_token %}
                            <input class="btn btn-link text-danger" type="submit" value="Remove" />
                        </form>
                    </li>
                {% endfor %}
            </ul>

            {% if select_card_form.fields.card.choices|length == 0 %}
                <p>There are no payment methods available. Please register one <a href="{% url 'payments:add_card' %}">here</a>.</p>
            {% else %}
                <form method="post" action="{% url 'payments:order' %}">
                    {% csrf_token %}
                    {{ select_card_form.as_p }}
                    <input type="submit" value="Order" />
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

web-ecommerce-app/products/templates/products/details.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ product.name }}</title>
{% endblock %}

{% block content %}
    <div class="container">
        <p><strong>Name:</strong> {{ product.name }}</p>
        <p><strong>Price:</strong> {{ product.price }} RON</p>
        <p><strong>Store:</strong> {{ product.store.name }}</p>
        <p><strong>Store Owner:</strong> {{ product.store.owner.username }}</p>
        <p><strong>Categories</strong></p>
        <ul>
            {% for category in product.categories.all %}
                <li>{{ category.name }} ({{ category.extra_column }})</li>
            {% endfor %}
        </ul>
        {% comment %}
        <ul>
            {% for category_pivot in product.categories_pivot.all %}
                <li>{{ category_pivot.category.name }} ({{ category_pivot.extra_column }})</li>
            {% endfor %}
        </ul>
        {% endcomment %}
    </div>
{% endblock %}

web-ecommerce-app/products/templates/products/products.html
{% extends 'base.html' %}

{% block title %}
    <title>My Products Page</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>My Products Page</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form method="get" action="{% url 'products:all' %}">
                    {{ form.as_p }}
                    <input type="submit" value="Apply filters" />
                </form>
            </div>
        </div>
        {% if page_obj.paginator.num_pages > 1 %}
            <div class="row">
                <div class="col-12">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'products:all' %}?page={{page_obj.previous_page_number}}">Previous page</a>
                    {% else %}
                        <div>This is the first page.</div>
                    {% endif %}
                    <div class="text-danger">Current page: {{ page_obj.number }}</div>
                    {% if page_obj.has_next %}
                        <a href="{% url 'products:all' %}?page={{page_obj.next_page_number}}">Next page</a>
                    {% else %}
                        <div>This is the last page.</div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
        <ul class="row">
            {% for product in page_obj %}
                <li style="margin-bottom: 10px;" class="col-12 col-md-6">
                    <div>
                        {{ product.name }} - {{ product.price }} RON <a href="{% url 'products:details' product.id %}">View product</a>
                    </div>
                    <div>
                        Extra details:
                        <ul>
                            <li>
                                Color: {{ product.color }}
                            </li>
                            <li>
                                Size: {{ product.human_size }}
                            </li>
                            <li>
                                Gender: {{ product.gender }}
                            </li>
                        </ul>
                    </div>
                    <div>
                        <form method="post" action="{% url 'products:add_to_cart' product.id %}">
                            {% csrf_token %}
                            <input type="number" value="0" name="quantity" />
                            <input type="submit" value="Add to cart" />
                        </form>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}