web-ecommerce-app/api/urls.py
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter
from api.register import RegisterViewSet
from api.products import ProductViewSet

router = DefaultRouter()
router.register(r'register', RegisterViewSet, basename='register')
router.register(r'products', ProductViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('browser-auth/', include('rest_framework.urls')),
    path('auth/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

web-ecommerce-app/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt
from ecommerce.views import homepage_view

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('my_admin.urls')),
    path('', homepage_view),
    path('products/', include('products.urls')),
    path('stores/', include('stores.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
    path('payments/', include('payments.urls')),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-ecommerce-app/payments/urls.py
from django.urls import path
from payments.views import (
    add_card, show_cards, delete_card, order, process, handle_succeeded_payment, handle_failed_payment,
    show_orders, show_order_details
)

app_name = 'payments'

urlpatterns = [
    path('add-card/', add_card, name='add_card'),
    path('cards/', show_cards, name='cards'),
    path('delete_card/<int:card_id>/', delete_card, name='delete_card'),
    path('order/', order, name='order'),
    path('process/', process, name='process'),
    path('succeeded/', handle_succeeded_payment, name='succeeded'),
    path('failed/', handle_failed_payment, name='failed'),
    path('orders/', show_orders, name='orders'),
    path('orders/<int:order_id>/', show_order_details, name='order_details'),
]

web-ecommerce-app/products/urls.py
from django.urls import path
from products.views import show_all_products, show_product_details, add_product_to_cart, show_checkout, remove_product_from_cart

app_name = 'products'

urlpatterns = [
    path('', show_all_products, name='all'),  # this is already localhost:8000/products/
    path('<int:product_id>/', show_product_details, name='details'),
    path('<int:product_id>/add_to_cart', add_product_to_cart, name='add_to_cart'),  # localhost:8000/products/<p_id>/add_to_cart
    path('checkout/', show_checkout, name='checkout'),
    path('<int:product_id>/remove_from_cart/', remove_product_from_cart, name='remove_from_cart'),
]

web-ecommerce-app/payments/models.py
from uuid import uuid4
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product
from ecommerce.models import TimestampModel

AuthUserModel = get_user_model()


class StripeCustomer(models.Model):
    user = models.OneToOneField(AuthUserModel, on_delete=models.CASCADE, related_name='stripe_customer')
    stripe_id = models.CharField(max_length=255, default=None, null=True)


class StripeCard(models.Model):
    stripe_customer = models.ForeignKey(StripeCustomer, on_delete=models.CASCADE, related_name='cards')
    stripe_id = models.CharField(max_length=255, default=None, null=True)
    last4 = models.CharField(max_length=4, default=None, null=True)
    exp_month = models.IntegerField(default=None, null=True)
    exp_year = models.IntegerField(default=None, null=True)

    @property
    def number(self):
        # return '**** **** **** ' + str(self.last4)
        return '**** ' * 3 + str(self.last4)


class Order(TimestampModel):
    user = models.ForeignKey(AuthUserModel, on_delete=models.SET_NULL, null=True, default=None, related_name='orders')
    number = models.CharField(max_length=50, null=True, default=uuid4)

    def human_date(self):
        return self.created_at.strftime('%Y-%m-%d %H:%M:%S')
    human_date.short_description = 'date'
    human_date.admin_order_field = 'created_at'

    def currency_amount(self):
        return f'{self.amount} RON'
    currency_amount.short_description = 'Price'

    @property
    def amount(self):
        total = sum([
            float(item.price) * item.quantity
            for item in self.items.all()
        ])

        return '%.2f' % total


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, default=None, related_name='product')
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    @property
    def product_name(self):
        if self.product is None:
            return 'Unknown'

        return self.product.name


class Report(TimestampModel):
    user = models.ForeignKey(AuthUserModel, on_delete=models.SET_NULL, null=True, default=None)
    file = models.FileField(upload_to='reports', null=False)

    def __str__(self):
        return self.file.name

web-ecommerce-app/payments/views.py
import json
import stripe
from django.shortcuts import render, redirect, reverse, Http404, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from payments.models import StripeCard, Order
from payments.utils import get_user_payment_methods_details
from products.forms import SelectCardForm
from utils.cart import Cart


@login_required
def add_card(request):
    if request.method == 'POST':
        if 'stripeToken' not in request.POST:
            raise Http404('Method not allowed')

        stripe_token = request.POST['stripeToken']
        stripe_customer_id = request.user.stripe_customer.stripe_id

        card = stripe.Customer.create_source(
            stripe_customer_id,
            source=stripe_token,
            api_key=settings.STRIPE_SECRET_KEY,
        )

        StripeCard.objects.create(
            stripe_customer=request.user.stripe_customer,
            stripe_id=card['id'],
            last4=card['last4'],
            exp_month=card['exp_month'],
            exp_year=card['exp_year'],
        )

        return redirect(reverse('payments:cards'))

    return render(request, 'payments/add_card.html', {
        'stripe_key': settings.STRIPE_PUBLIC_KEY
    })


@login_required
def show_cards(request):
    cards = get_user_payment_methods_details(request.user)

    return render(request, 'payments/cards.html', {
        'cards': cards,
    })


@login_required
def delete_card(request, card_id):
    card = get_object_or_404(StripeCard, pk=card_id)

    if card.stripe_customer.user.id != request.user.id:
        raise Http404('Card was not found.')

    stripe.Customer.delete_source(
        card.stripe_customer.stripe_id,
        card.stripe_id,
        api_key=settings.STRIPE_SECRET_KEY,
    )

    card.delete()

    return redirect(reverse('payments:cards'))


@login_required
def order(request):
    if request.method == 'POST':
        select_card_form = SelectCardForm(request.user, data=request.POST)

        if select_card_form.is_valid():
            # create PaymentIntent
            stripe_card = select_card_form.cleaned_data.get('card')

            cart = Cart(request)
            db_order, order_amount = cart.create_order()
            return_url = f'{settings.LOCALHOST_DOMAIN}{reverse("payments:process")}'

            payment_intent = stripe.PaymentIntent.create(
                amount=int(order_amount * 100),
                currency="ron",
                payment_method_types=["card"],
                payment_method=stripe_card.stripe_id,
                confirm=True,
                return_url=return_url,
                customer=request.user.stripe_customer.stripe_id,
                description=json.dumps({
                    'order': {
                        'id': db_order.id
                    },
                }),
                api_key=settings.STRIPE_SECRET_KEY,
            )

            next_action = payment_intent.get('next_action', {})
            if 'redirect_to_url' in next_action and 'url' in next_action['redirect_to_url']:
                return redirect(next_action['redirect_to_url']['url'])

            return f"{redirect(reverse('payments:process'))}?payment_intent={payment_intent['id']}"

        return redirect(reverse('products:checkout'))

    raise Http404('Method not allowed!')


def process(request):
    if 'payment_intent' in request.GET:
        payment_intent = stripe.PaymentIntent.retrieve(
            request.GET['payment_intent'],
            api_key=settings.STRIPE_SECRET_KEY
        )

        if payment_intent['last_payment_error'] is None:
            return redirect(reverse('payments:succeeded'))

        print("payment_intent['last_payment_error']", payment_intent['last_payment_error'])
        return redirect(reverse('payments:failed'))

    raise Http404('Method not allowed!')


def handle_succeeded_payment(request):
    return HttpResponse('Payment succeeded.')


def handle_failed_payment(request):
    return HttpResponse('Payment failed.')


@login_required
def show_orders(request):
    orders = request.user.orders.all()

    return render(request, 'payments/orders.html', {
        'orders': orders,
    })


@login_required
def show_order_details(request, order_id):
    db_order = get_object_or_404(Order, pk=order_id)

    if db_order.user.id != request.user.id:
        raise Http404('Order not available.')

    return render(request, 'payments/order_details.html', {
        'order': db_order,
    })

web-ecommerce-app/payments/templates/payments/add_card.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form action="{% url 'payments:add_card' %}" method="post" id="payment-form">
                {% csrf_token %}
                <div class="form-row">
                    <label for="card-element">
                        Credit or debit card
                    </label>
                    <div id="card-element" class="form-group form-control">
                        <!-- A Stripe Element will be inserted here. -->
                    </div>
                    <!-- Used to display form errors. -->
                    <div id="card-errors" role="alert"></div>
                </div>
                <button>Add card</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block bscript %}
<script src="https://js.stripe.com/v3/"></script>
<script stripeKey="{{ stripe_key }}" src="{% static 'payments/js/cardElement.js' %}"></script>
{% endblock %}

web-ecommerce-app/payments/templates/payments/cards.html
{% extends 'base.html' %}

{% block content %}
    {% if cards|length > 0 %}
        <ul>
            {% for card in cards %}
                <li style="margin-bottom: 20px;">
                    <div><strong>Card number:</strong> {{ card.number }}</div>
                    <div><strong>Expires on:</strong> {{ card.exp_month }}/{{ card.exp_year }}</div>
                    <form method="post" action="{% url 'payments:delete_card' card.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Remove" />
                    </form>
                </li>
            {% endfor %}
        </ul>
        <p>
            You can add another card <a href="{% url 'payments:add_card' %}">here</a>.
        </p>
    {% else %}
        <p>You don't have any available payment methods. Please register one <a href="{% url 'payments:add_card' %}">here</a>.</p>
    {% endif %}
{% endblock %}

web-ecommerce-app/payments/templates/payments/order_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div><strong>Total price:</strong> {{ order.amount }} RON</div>
        <ul>
            {% for item in order.items.all %}
            <li style="margin-bottom: 20px">
                <div>
                    <strong>Name:</strong>
                    {% if item.product %}
                        <a href="{% url 'products:details' item.product.id %}">{{ item.product.name }}</a>
                    {% else %}
                        Unavailable
                    {% endif %}
                </div>
                <div><strong>Price:</strong> {{ item.price }} RON</div>
                <div><strong>Quantity:</strong> {{ item.quantity }}</div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

web-ecommerce-app/payments/templates/payments/orders.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <ul>
            {% for order in orders %}
                <li style="margin-bottom: 20px;">
                    <div>Total: {{ order.amount }} RON</div>
                    <a href="{% url 'payments:order_details' order.id %}">View details</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}